import 'package:flutter/material.dart';

class BColorSchemeTheme {
  BColorSchemeTheme._();
  static ColorScheme lightColorSchemeTheme = ColorScheme.fromSeed(
    seedColor: const Color.fromRGBO(255, 230, 0, 0.7),
    brightness: Brightness.light,
    //primary: const Color.fromRGBO(255, 230, 0, 0.4),
    primary: const Color(0xFF673AB7),
    
    onPrimary: const Color(0xFFFFFFFF),
    primaryContainer: const Color(0xFFEADDFF),
    onPrimaryContainer: const Color(0xFF21005D),
    secondary: const Color(0xFF625B71),
    onSecondary: const Color(0xFFFFFFFF),
    secondaryContainer: const Color(0xFFE8DEF8),
    onSecondaryContainer: const Color(0xFF1D192B),
    tertiary: const Color(0xFF7D5260),
    onTertiary: const Color(0xFFFFFFFF),
    tertiaryContainer: const Color(0xFFFFD8E4),
    onTertiaryContainer: const Color(0xFF31111D),
    error: const Color(0xFFB3261E),
    onError: const Color(0xFFFFFFFF),
    errorContainer: const Color(0xFFF9DEDC),
    onErrorContainer: const Color(0xFF410E0B),
    background: const Color(0xFFFFFBFE),
    onBackground: const Color(0xFF1C1B1F),
    surface: const Color(0xFFFFFBFE),
    onSurface: const Color(0xFF1C1B1F),
    surfaceVariant: const Color(0xFFE7E0EC),
    onSurfaceVariant: const Color(0xFF49454F),
    outline: const Color(0xFF79747E),
    outlineVariant: const Color(0xFFCAC4D0),
    shadow: const Color(0xFF000000),
    scrim: const Color(0xFF000000),
    inverseSurface: const Color(0xFF313033),
    onInverseSurface: const Color(0xFFF4EFF4),
    inversePrimary: const Color(0xFFD0BCFF),
    // The surfaceTint color is set to the same color as the primary.
    surfaceTint: const Color(0xFF6750A4),
  );

  static ColorScheme darkColorSchemeTheme = ColorScheme.fromSeed(
    seedColor: const Color.fromRGBO(255, 255, 255, 1),
    brightness: Brightness.dark,
    primary: const Color.fromRGBO(255, 230, 0, 1),

    //primary: const Color(0xFFD0BCFF),
    onPrimary: const Color(0xFF381E72),
    primaryContainer: const Color(0xFF4F378B),
    onPrimaryContainer: const Color(0xFFEADDFF),
    secondary: const Color(0xFFCCC2DC),
    onSecondary: const Color(0xFF332D41),
    secondaryContainer: const Color(0xFF4A4458),
    onSecondaryContainer: const Color(0xFFE8DEF8),
    tertiary: const Color(0xFFEFB8C8),
    onTertiary: const Color(0xFF492532),
    tertiaryContainer: const Color(0xFF633B48),
    onTertiaryContainer: const Color(0xFFFFD8E4),
    error: const Color(0xFFF2B8B5),
    onError: const Color(0xFF601410),
    errorContainer: const Color(0xFF8C1D18),
    onErrorContainer: const Color(0xFFF9DEDC),
    background: const Color(0xFF1C1B1F),
    onBackground: const Color(0xFFE6E1E5),
    surface: const Color(0xFF1C1B1F),
    onSurface: const Color(0xFFE6E1E5),
    surfaceVariant: const Color(0xFF49454F),
    onSurfaceVariant: const Color(0xFFCAC4D0),
    outline: const Color(0xFF938F99),
    outlineVariant: const Color(0xFF49454F),
    shadow: const Color(0xFF000000),
    scrim: const Color(0xFF000000),
    inverseSurface: const Color(0xFFE6E1E5),
    onInverseSurface: const Color(0xFF313033),
    inversePrimary: const Color(0xFF6750A4),
    // The surfaceTint color is set to the same color as the primary.
    surfaceTint: const Color(0xFFD0BCFF),
  );
}
